name: 'Integration Tests'

# Notes:
#  https://github.community/t5/GitHub-Actions/Github-Actions-services-not-reachable/m-p/30739/highlight/true#M538

on:
  pull_request:
    branches:
      - master
      - next

jobs:
  baseline:
    name: Baseline Tests
    runs-on: ubuntu-latest

    services:
      openldap:
        image: docker.pkg.github.com/ldapjs/docker-test-openldap/openldap:1.0
        ports:
          - 389:389
          - 636:636

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npm run test:integration
